---
title: "TextMining"
author: "Ted"
date: "2018年7月14日"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## **網路爬蟲**
******

```{r, message=FALSE, results='hide'}
source("C:\\Users\\TEMP\\Desktop\\qq\\106Summer-master\\106Summer-master\\week2\\pttTestFunction.R")
id = c(4430:4440)
URL = paste0("https://www.ptt.cc/bbs/Stock/index", id, ".html")
filename = paste0(id, ".txt")
pttTestFunction(URL[1], filename[1])
mapply(pttTestFunction, 
       URL = URL, filename = filename)
```

## **文本清理**
******

```{r, message=FALSE, warning=FALSE}
rm(list=ls(all.names = TRUE))
library(NLP)
library(tm)
library(jiebaRD)
library(jiebaR)
library(RColorBrewer)
library(wordcloud)
filenames <- list.files(getwd(), pattern="*.txt")
files <- lapply(filenames, readLines)
docs <- Corpus(VectorSource(files))

#新增詞彙
cutter= worker("tag")
mynewwords <- c("法人", "短線", "看好", "看漲", "股東會", "進場", "有限公司", "有跟到", "現在", "現金")
new_user_word(cutter, mynewwords)

#移除可能有問題的符號
toSpace <- content_transformer(function(x, pattern) {
  return (gsub(pattern, " ", x))
}
)
docs <- tm_map(docs, toSpace, "※")
docs <- tm_map(docs, toSpace, "◆")
docs <- tm_map(docs, toSpace, "‧")
docs <- tm_map(docs, toSpace, "的")
docs <- tm_map(docs, toSpace, "我")
docs <- tm_map(docs, toSpace, "是")
docs <- tm_map(docs, toSpace, "看板")
docs <- tm_map(docs, toSpace, "作者")
docs <- tm_map(docs, toSpace, "發信站")
docs <- tm_map(docs, toSpace, "批踢踢實業坊")
docs <- tm_map(docs, toSpace, "[a-zA-Z]")
#移除標點符號 (punctuation)
#移除數字 (digits)、空白 (white space)
docs <- tm_map(docs, removePunctuation)
docs <- tm_map(docs, removeNumbers)
docs <- tm_map(docs, stripWhitespace)
#移除文字
docs <- tm_map(docs, toSpace,  "推")
docs <- tm_map(docs, toSpace,"了")
docs <- tm_map(docs, toSpace, "就")
docs <- tm_map(docs, toSpace,"都")
docs <- tm_map(docs, toSpace,"不")
docs <- tm_map(docs, toSpace, "在")
docs <- tm_map(docs, toSpace, "你")
docs <- tm_map(docs, toSpace, "也")
docs <- tm_map(docs, toSpace, "要")
docs <- tm_map(docs, toSpace,  "嗎")
docs <- tm_map(docs, toSpace,  "有")
docs <- tm_map(docs, toSpace,"會")
docs <- tm_map(docs, toSpace, "還")
docs <- tm_map(docs, toSpace, "好")
docs <- tm_map(docs, toSpace, "說")
docs <- tm_map(docs, toSpace, "看")
docs <- tm_map(docs, toSpace, "只")
docs <- tm_map(docs, toSpace, "人")
docs <- tm_map(docs, toSpace,"啊")
docs <- tm_map(docs, toSpace, "跟")
docs <- tm_map(docs, toSpace, "真")
docs <- tm_map(docs, toSpace, "可以")
docs <- tm_map(docs, toSpace, "但")
docs <- tm_map(docs, toSpace, "多")
docs <- tm_map(docs, toSpace, "噓")
docs <- tm_map(docs, toSpace,"又")
docs <- tm_map(docs, toSpace,"很")
docs <- tm_map(docs, toSpace, "被")
docs <- tm_map(docs, toSpace, "怎麼")
docs <- tm_map(docs, toSpace,"大家")
docs <- tm_map(docs, toSpace, "啦")
docs <- tm_map(docs, toSpace, "才")
docs <- tm_map(docs, toSpace, "多")
docs <- tm_map(docs, toSpace, "個")
docs <- tm_map(docs, toSpace, "年")
docs <- tm_map(docs, toSpace, "月")
docs <- tm_map(docs, toSpace, "為")
docs <- tm_map(docs, toSpace, "文章")
docs <- tm_map(docs, toSpace, "覺得")
docs <- tm_map(docs, toSpace, "什麼")
docs <- tm_map(docs, toSpace, "沒")
docs <- tm_map(docs, toSpace, "到")
docs <- tm_map(docs, toSpace, "這")
docs <- tm_map(docs, toSpace, "現")
docs <- tm_map(docs, toSpace, "大")
docs <- tm_map(docs, toSpace, "能")
docs <- tm_map(docs, toSpace, "來")
docs <- tm_map(docs, toSpace, "吧")
docs <- tm_map(docs, toSpace, "去")
docs <- tm_map(docs, toSpace, "他")
docs <- tm_map(docs, toSpace, "再")
docs <- tm_map(docs, toSpace, "上")
docs <- tm_map(docs, toSpace, "可")

```

## **詞頻矩陣**
******

```{r}
mixseg = worker()
jieba_tokenizer=function(d){
  unlist(segment(d[[1]],mixseg))
}
seg = lapply(docs, jieba_tokenizer)
freqFrame = as.data.frame(table(unlist(seg)))
freqFrame = freqFrame[order(freqFrame$Freq,decreasing=TRUE), ]
library(knitr)
kable(head(freqFrame), format = "markdown")
```

## **文字雲**
*****

```{r, warning=FALSE, error=FALSE}
wordcloud(freqFrame$Var1,freqFrame$Freq,
          scale=c(5,0.1),min.freq=100,max.words=100,
          random.order=FALSE, random.color=FALSE, 
          rot.per=.3, colors=brewer.pal(10, "Dark2"),
          ordered.colors=FALSE,use.r.layout=FALSE,
          fixed.asp=TRUE)
```


